"""changed userloader in users table

Revision ID: 9b84e1a6a6cb
Revises: cf3e2407bbd3
Create Date: 2018-09-17 12:09:24.538518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b84e1a6a6cb'
down_revision = 'cf3e2407bbd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_timestamp', table_name='messages')
    op.drop_table('messages')
    op.drop_column('posts', 'last_message_read_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('last_message_read_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('body', sa.VARCHAR(length=140), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name='messages_recipient_id_fkey'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name='messages_sender_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='messages_pkey')
    )
    op.create_index('ix_messages_timestamp', 'messages', ['timestamp'], unique=False)
    # ### end Alembic commands ###
